version: '3'
services:
  web:
    ports:
     - "8888:80" #8888可修改为任意想要开放的端口
    environment: &sql_config
      MYSQL_USER_PASS : 'fhaw8fgw7961t79g' #设置管理员密码
      MYSQL_USER_NAME : 'root_sql'
      MYSQL_USER_DB : '`xss-platform`'
      CREATE_MYSQL_BASIC_USER_AND_DB : "true"
    build:
      context: .
      args:
        MYSQL_USER_PASS : 'fhaw8fgw7961t79g' #设置管理员密码
    volumes:
     - ./mysql:/var/lib/mysql
     - ./initPlat.sh:/initPlat.sh